### ISSUE TITLE
MD5 authentication support in OpenNTPd

### ISSUE THREAD

**Issue by keithnoguchi** [openntpd-portable/openntpd-openbsd#6]
Hi Brent,

I don't know this is the right place to ask the feature related question but can't find it from [the official page](http://www.openntpd.org).

As mentioned in the [reference ntpd page](http://support.ntp.org/bin/view/Support/OpenNTPD), I don't believe we have a MD5 authentication support in the [optnntpd](http://www.openntpd.org).  I believe this is because [openntpd](http://www.openntpd.org) doesn't believe it's the preferred way to secure the NTP protocol but do you think the project willing to upstream those features, if I develop that feature?

Of do you recommend to try other project, say reference implementation, if MD5 authentication support is vital?

Thank you for your time and hope to hear from you soon.

Cheers,

**Comment by busterb** [comment]
@keinohguchi, I suspect this project will be unlikely to adopt MD5 auth support. I'd check the OpenBSD tech@ mailing list though, rather than this github projects, since it is just a mirror of the OpenBSD source. Thanks.
